#
# This compose builds base ML images for development and testing.
#
version: "3.9"
services:
  #
  # Base and development containers.
  #
  base: &base
    build:
      context: .
      dockerfile: py310-debian.dockerfile
    volumes:
    - .:/home/jupyter
    environment:
      TERM: linux
    # entrypoint: sleep infinity
    working_dir: /home/jupyter
    cap_add:
    - SYS_PTRACE
  debian:
    image: ml-playground:py310-debian
    <<: *base
  spacy:
    <<: *base
    build:
      context: .
      dockerfile: py310-spacy.dockerfile
      args:
        - BASEIMAGE=ml-playground
  test:
    <<: *base
    environment:
      TERM: linux
      VIRTUALENV_SYSTEM_SITE_PACKAGES: "True"
    command: ["tox", "-e", "py3"]
  super-linter:
    image: github/super-linter:v3.15.5
    environment:
    - RUN_LOCAL=true
    - VALIDATE_MARKDOWN=false
    - VALIDATE_PYTHON_ISORT=false
    - VALIDATE_XML=false
    - VALIDATE_NATURAL_LANGUAGE=false
    - IGNORE_GITIGNORED_FILES=true
    volumes:
    - .:/tmp/lint/
    - ./tox.ini:/action/lib/.automation/.flake8
