#
# Build image with Cloud Build.
#
# Run with:
#
# $ gcloud build submit --config docs/cloudbuild.yaml .
#
steps:
- name: 'gcr.io/cloud-builders/docker'
  # At build time, Cloud Build automatically replaces
  #  $PROJECT_ID with your project ID;
  #  see https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values for more info.
  args: [ 'build',
    '-t', 'europe-west12-docker.pkg.dev/$PROJECT_ID/$_REGISTRY_ID/mlai-python310:py310',
    '--file', 'py310-debian.dockerfile',
    '.' ]
  env:
  - 'DOCKER_BUILDKIT=1'
images:
- 'europe-west12-docker.pkg.dev/$PROJECT_ID/$_REGISTRY_ID/mlai-python310:py310'
